// Add your backend endpoints, make sure the endpoints DO NOT end with a '/' the endpoint should end with '.com'
export const LinkGatewayEndpoint = 'https://protected-coast-11752.herokuapp.com'
export const AnchorGatewayEndpoint = 'https://pure-forest-09637.herokuapp.com'
export const NodeGatewayEndpoint = 'https://boiling-sands-61339.herokuapp.com'
export const ImmutableGridGatewayEndpoint = 'https://stark-savannah-73845.herokuapp.com'